release:
  header: |
    ## depsdev {{ .Tag }} 🥳
    *CLI client (and Golang module) for deps.dev API. Free access to dependencies, licenses, advisories, and other critical health and security signals for open source package versions.*

  footer: |
    If you encounter a problem, just open an [issue](https://github.com/edoardottt/depsdev/issues)

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
    binary: "{{ .ProjectName }}"
    main: ./main.go

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256
