name: depsdev
summary: CLI client for deps.dev API
description: |
      CLI client for deps.dev API.
      Free access to dependencies, licenses, advisories, and other critical health and security signals for open source package versions.
version: 0.2.0
grade: stable
base: core20

confinement: strict

apps:
  depsdev:
    command: bin/depsdev
    plugs:
      - home
      - network

parts:
  depsdev:
    plugin: go
    source-type: git
    source: https://github.com/edoardottt/depsdev